### PR TITLE
Fix Random button on Main page.

### LINKED ISSUE #78: Random button functionality broken.
### Steps to reproduce

1. Launch cloudstream beta and Random button disappears after homepage is loaded.
2. Toggling "Show Random button on homepage" does not make any difference.
3. On filter provider on homepage, select "random" option. It resets provider to "none".

### Expected behavior

There is an issue with both the "Show random button on homepage" option (Floating action button on left on homepage) and "Random" option in Provider chooser (Floating action button on right on homescreen which is used to choose provider to show contents from on homepage).
Expected - 
1. Show random button(LHS FAB) - should randomly open view page of a movie/series 
2. Random option (In RHS FAB) - should randomly choose a provider based in category chosen (i.e. movie/series etc)

Both behaviours are working as expected in the last stable release of cloudstream (v 3.0.0)

### Actual behavior

1. Show random button(LHS FAB) - sometimes briefly shows up when app is launched but always disappears after homepage is loaded.
2. Random option (In RHS FAB) - selects "none" as provider.

### Cloudstream version and commit hash

3.1.4 cdf0047

### Android version

Android 9

### Logcat

```java
NA
```

### Other details

NA

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Jacekun**
Fix #78

### CODE REVIEW

File: app/src/main/java/com/lagradost/cloudstream3/ui/home/HomeFragment.kt [hunk 1]
```diff
@@ -521,15 +521,13 @@ class HomeFragment : Fragment() {
...
         context?.let {
             val settingsManager = PreferenceManager.getDefaultSharedPreferences(it)
             toggleRandomButton =
                 settingsManager.getBoolean(getString(R.string.random_button_key), false)
-            home_random?.isVisible = toggleRandomButton
-            if (!toggleRandomButton) {
-                home_random?.visibility = View.GONE
-            }
+            home_random?.isVisible = false
+            home_random?.visibility = View.GONE
```
Comment (LagradOst) [inline app/src/main/java/com/lagradost/cloudstream3/ui/home/HomeFragment.kt:530]: why duplicate call here?

Comment (Jacekun) [reply app/src/main/java/com/lagradost/cloudstream3/ui/home/HomeFragment.kt:530]: No reason. Just copied the line out of the ``if`` condition. Will remove the `home_random?.isVisible = false` though

**Review by LagradOst — APPROVED** [review]
LGTM, ready to merge?
