### PR TITLE
Fixed shared pool, closes #2082

### LINKED ISSUE #2082: Changing theme doesn't immediately change colors in all places
### Steps to reproduce

1. Change theme from dark or light or vice versa
2. Go somewhere like to extensions or the home page in some cases

### Expected behavior

The colors should be changed to new theme colors.

### Actual behavior

The remain on the old theme colors until, in some cases like the home page, you leave an reenter fragment again, or in other cases until you restart the app entirely.

Image
Image
Image
Image
Image

### Cloudstream version and commit hash

4.6.1 6c30af3

### Android version

Android 16

### Logcat

```java

```

### Other details

_No response_

### Acknowledgements

- [x] I am sure my issue is related to the app and **NOT some extension**.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by LagradOst**
This should fix all the sharedPool issues without clearing them. The problem is that views are shared between context barriers, creating nonsense bugs like coil not rendering images, or cards rendering in the wrong theme. This is done with a `WeakHashMap<Context, RecyclerView.RecycledViewPool>` to map the context to the correct pool, and avoid storing a strong reference to the context. Moreover I used a lambda function as the constructor as it will be used several times. I have no idea why android do not do this by default. The implementation also uses synchronized to avoid any runtime crash, but this should never happen given that all UI should be done on the same thread.  

While I do not expect any bugs given that this fixed my issues in QN, there might be some views that are not rendered correctly in some specific circumstance. As such any testing would be appreciated. If you can get a view to render with the wrong image or with the wrong theme, then ping me.

### CODE REVIEW

File: app/src/main/java/com/lagradost/cloudstream3/ui/BaseAdapter.kt [hunk 1]
```diff
@@ -22,6 +24,33 @@ abstract class NoStateAdapter<T : Any>(
...
+ * The reason for this complicated structure is that a pool should not be shared between contexts
+ * as it makes coil fuck up, and theming.
+ * */
+fun newSharedPool(lambda: RecyclerView.RecycledViewPool.() -> Unit = { }): Pair<WeakHashMap<Context, RecyclerView.RecycledViewPool>, RecyclerView.RecycledViewPool.() -> Unit> =
+    WeakHashMap<Context, RecyclerView.RecycledViewPool>() to lambda
+
+/** Sets the shared pool of the recyclerview */
+fun RecyclerView.setRecycledViewPool(pool: Pair<WeakHashMap<Context, RecyclerView.RecycledViewPool>, RecyclerView.RecycledViewPool.() -> Unit>) {
+    val ctx = context ?: return
+    synchronized(pool.first) {
```
Comment (fire-light42) [inline app/src/main/java/com/lagradost/cloudstream3/ui/BaseAdapter.kt:38]: Locking a context object _may_ cause deadlocks or other unpredictable issues, since the context can be used literally everywhere else. 

In practice it seems to work well but I want to avoid any risks of weird issues arising from this.

Comment (fire-light42) [reply app/src/main/java/com/lagradost/cloudstream3/ui/BaseAdapter.kt:38]: Nevermind, I got confused by the nested types. You are locking on `WeakHashMap<Context, RecyclerView.RecycledViewPool>`, which will not cause issues.
