### PR TITLE
Fix STATE_IDLE issues in player

### LINKED ISSUE #2175: Closing media notification breaks ability to resume player
### Steps to reproduce

1. Play a video
2. Pause the video
3. Swipe the media notification in device status bar to clear it
4. Try to resume in player

### Expected behavior

Video should resume

### Actual behavior

The play button doesn't do anything anymore.

### Cloudstream version and commit hash

4.6.1 52100dc

### Android version

Android 16

### Logcat

```java

```

### Other details

_No response_

### Acknowledgements

- [x] I am sure my issue is related to the app and **NOT some extension**.
- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [x] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Luna712**
Fixes #2175  and also other issues

### CODE REVIEW

**Comment by Luna712** [comment]
Would like to also note that while it works it is kinda also a PoC, if anyone elese has a better idea here would love to hear it, I spent a long time debugging a few of these issues and this is just what solution I landed up on to fix it. But may not be the best way.

File: app/src/main/java/com/lagradost/cloudstream3/ui/player/CS3IPlayer.kt [hunk 1]
```diff
@@ -961,6 +961,21 @@ class CS3IPlayer : IPlayer {
...
+                        // STATE_IDLE. A bare play() call is a no-op in that state, re-prepare and
+                        // then resume to the saved position once we are in STATE_READY again.
+                        if (playbackState == Player.STATE_IDLE) {
+                            prepare()
+                            exoPlayer?.addListener(object : Player.Listener {
+                                private var seekApplied = false
+                                override fun onPlaybackStateChanged(playbackState: Int) {
+                                    if (seekApplied || playbackState != Player.STATE_READY) return
+                                    seekApplied = true
+                                    exoPlayer?.seekTo(currentWindow, playbackPosition)
```
Comment (Luna712) [inline app/src/main/java/com/lagradost/cloudstream3/ui/player/CS3IPlayer.kt]: This is broken logic right now I just realized also. It will re seek to whatever it was when it started since playbackPosition doesn't change. Will look into that later.

File: app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt [hunk 2]
```diff
@@ -393,6 +393,16 @@ class GeneratorPlayer : FullScreenPlayer() {
                     }
                 }
             })
+            .setNotificationListener(object : PlayerNotificationManager.NotificationListener {
+                override fun onNotificationCancelled(notificationId: Int, dismissedByUser: Boolean) {
+                    if (dismissedByUser) {
```
Comment (Luna712) [inline app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt]: Hmm... maybe this is actually worse then it being inconsistent and coming back. This could also mean if the notification is swiped while paused then when resumed it doesnt come back. I have noticed it randomly come back 10 minutes later without ever resuming it which is what this was for but maybe that is a better outcome. Not sure.

At the minimum we should fix STATE_IDLE issues anyway which causes other breakage of the resume button beyond just #2175 as well.

File: app/src/main/java/com/lagradost/cloudstream3/ui/player/CS3IPlayer.kt (hunk 1 above)
Comment (Luna712) [reply app/src/main/java/com/lagradost/cloudstream3/ui/player/CS3IPlayer.kt]: Fixed.

File: app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt (hunk 2 above)
Comment (Luna712) [reply app/src/main/java/com/lagradost/cloudstream3/ui/player/GeneratorPlayer.kt]: Removed this part now.

**Review by fire-light42 — APPROVED** [review]
