### PR TITLE
fix: can not switch subtitle after integrate ffmpeg decoder.

### LINKED ISSUE #531: Subtitles not working/ Downloading
It appears that after the recent pre-release update, subtitles are not working/ downloading. Can you please check. Also can you provide the way to revert to previous apk.

### PR DESCRIPTION
**Pull request by d4rkk3y**
fix #531 without revert #528

### CODE REVIEW

**Comment by self-similarity** [comment]
:partying_face:

File: app/src/main/java/com/lagradost/cloudstream3/ui/player/CS3IPlayer.kt [hunk 1]
```diff
@@ -662,12 +663,7 @@ class CS3IPlayer : IPlayer {
 
         private fun getTrackSelector(context: Context, maxVideoHeight: Int?): TrackSelector {
             val trackSelector = DefaultTrackSelector(context)
-            trackSelector.parameters = DefaultTrackSelector.ParametersBuilder(context)
-                // .setRendererDisabled(C.TRACK_TYPE_VIDEO, true)
-                .setRendererDisabled(C.TRACK_TYPE_TEXT, true)
```
Comment (LagradOst) [inline app/src/main/java/com/lagradost/cloudstream3/ui/player/CS3IPlayer.kt:667]: This seems to be the culprit and your patch works without the setTrackTypeDisabled
Are there any reasons to have those too?

Comment (d4rkk3y) [reply app/src/main/java/com/lagradost/cloudstream3/ui/player/CS3IPlayer.kt:667]: Without those two setTrackTypeDisabled when I choose `No Subtitles` in subtitle selection, player still show subtitle (maybe default subtitle).
