### PR TITLE
Reload library when reloading home

### LINKED ISSUE #650: Library doesn't reload when switching accounts
### Steps to reproduce

* Open library (with account1)
* Switch account
* Open Library again (with account2)

### Expected behavior

The library should now be from account2

### Actual behavior

The library is from account1 still, only restarting the app correctly gives library from account2 again.

### Cloudstream version and commit hash

4.2.0 3f51195

### Android version

Android 13

### Logcat

_No response_

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Luna712**
So that library is reloaded when switching accounts.

Fixes #650

### CODE REVIEW

File: app/src/main/java/com/lagradost/cloudstream3/utils/DataStoreHelper.kt [hunk 1]
```diff
@@ -131,7 +131,6 @@ object DataStoreHelper {
 
                             // update UI
                             setAccount(getDefaultAccount(context), true)
-                            MainActivity.bookmarksUpdatedEvent(true)
```
Comment (Luna712) [inline app/src/main/java/com/lagradost/cloudstream3/utils/DataStoreHelper.kt:134]: NOTE: This is removed because it is also done in setAccount so it was doing it twice. If that was incorrect, I will revert this part.

**Comment by Luna712** [comment]
I forgot to mention this as well, the reason I just used the reloadHomeEvent is to prevent having another one for library when it would only ever be used at the same time. I can update to create a different one if you want though.
