### PR TITLE
Set play button to first unwatched Episode on TV

### LINKED ISSUE #755: Play button doesn't currently show the next unwatched episode to play
### Steps to reproduce

The play button always seems to just say Episode 1 and does not change to the current unwatched episode when one becomes available.

[Screenshot_20231109-043718](https://github.com/recloudstream/cloudstream/assets/3983279/9eae4acd-8c5e-430f-a5e1-93ad3f1b132e)

### Expected behavior

When an unwatched episode is available it should say that episode instead of episode 1. If you mark if so's watched or watch them manually it should offer the next unwatched episode on the play button.

!

### Actual behavior

Currently if there are multiple watched episodes The play button does not offer the next unwatched episode.

### Cloudstream version and commit hash

4.2.1 11136fe

### Android version

Android 10 (Sony Bravia Google TV)

### Logcat

_No response_

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to pre-release version **[Latest](https://github.com/recloudstream/cloudstream/releases)**.
- [X] If related to a provider, I have checked the site and it works, but not the app.
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by KingLucius**
Fixes #755

### CODE REVIEW

File: app/src/main/java/com/lagradost/cloudstream3/ui/result/ResultFragmentTv.kt [hunk 1]
```diff
@@ -781,25 +781,28 @@ class ResultFragmentTv : Fragment() {
 
                 //    resultEpisodeLoading.isVisible = episodes is Resource.Loading
                 if (episodes is Resource.Success) {
-                    val first = episodes.value.firstOrNull()
-                    if (first != null) {
+
+                    val lastWatchedIndex = episodes.value.indexOfLast { ep -> ep.videoWatchState == VideoWatchState.Watched }
```
Comment (fire-light42) [inline app/src/main/java/com/lagradost/cloudstream3/ui/result/ResultFragmentTv.kt:785]: no? this will get you a wrong result as watchstate is seperate from watched. use getWatchProgress, getDisplayPosition or getRealPosition

Comment (fire-light42) [reply app/src/main/java/com/lagradost/cloudstream3/ui/result/ResultFragmentTv.kt:785]: watch state if smth that you manually toggle

**Review by fire-light42 — CHANGES_REQUESTED** [review]

File: app/src/main/java/com/lagradost/cloudstream3/ui/result/ResultFragmentTv.kt (hunk 1 above)
Comment (fire-light42) [reply app/src/main/java/com/lagradost/cloudstream3/ui/result/ResultFragmentTv.kt:785]: or did you mean watch state? because you need to specify that if that is the case

Comment (KingLucius) [reply app/src/main/java/com/lagradost/cloudstream3/ui/result/ResultFragmentTv.kt:785]: I want to get the last index of the "marked as watched" episode, then i return rhe next one so this will be the first unwatched

Comment (KingLucius) [reply app/src/main/java/com/lagradost/cloudstream3/ui/result/ResultFragmentTv.kt:785]: ep.videoWatchState become VideoWatchState.Watched after actual watching or use "Mark as watched"
both works

**Review by fire-light42 — APPROVED** [review]
